### ISSUE TITLE
Error in Matella after speaking into mic "PermissionError: [Errno 13] Permission denied: 'player_recording.wav"

### ISSUE THREAD

**Issue by BodyOfTheMany** [art-from-the-machine/Mantella#128]
In debug I can have a wonderful conversation. 
In game, when i speak after seeing 'listening...' I am directed to look at the mantella window to see an error
the error is as follows:

Traceback (most recent call last):
  File "main.py", line 178, in <module>
  File "src\stt.py", line 77, in get_player_response
  File "src\stt.py", line 107, in recognize_input
  File "src\stt.py", line 156, in _recognize_speech_from_mic
PermissionError: [Errno 13] Permission denied: 'player_recording.wav'

I'm unable to find any info about this error and would love any help you can provide! Thanks!

**Comment by teddybear082** [comment]
Almost always this is when you put all the mantella software into your mantella spell mod folder (and I think also when using Vortex).  If you did that, undo it.

**Comment by BodyOfTheMany** [comment]
Thanks teddybear! All I had to do to fix this was delete player_recording.wav and it worked like a charm! It was hanging onto a 'goodbye' from my last debug test.
