### ISSUE TITLE
Internal network LocalAI  as LLM Provider

### ISSUE THREAD

**Issue by maxi1134** [art-from-the-machine/Mantella#333]
Hi there,
I currently use [https://localai.io/ as ](https://github.com/mudler/LocalAI) as a basis for my LLM system.

I am wondering how hard it would be to integrate this with Mantella? This would reduce the load on my gaming PC using an  AMD card and send the LLM load to my server with a 3090.

Thanks!

**Comment by Leidtier** [comment]
I haven't looked deeper into it, but if it really is a
> Drop-in replacement for OpenAI
it provides an OpenAI compatible endpoint and you can already connect to it.

**Comment by maxi1134** [comment]
> Just set the `llm_api` config value to the address of the endpoint provided by LocalAI.

That was it, thanks!
