### ISSUE TITLE
v12 config.ini locations.

### ISSUE THREAD

**Issue by wiseman-timelord** [art-from-the-machine/Mantella#337]
Mantella v11 saves the config.ini in a safe location of the mantella dir, however, with regards to v12... 
- I moved my documents folder from C:\users\username\my documents\ to a different drive, and I did it the proper way, and for some reason when I installed Mantella v12 and run it, it insists upon using that vanilla windows docs dir on C: for `config.ini`. No other programs are having this issue, and when I click on the fav link for documents, it is not the one with mantella in it, its the correct one on the other drive.

**Comment by Leidtier** [comment]
Thanks for reporting, I'll take a look at it.

**Comment by wiseman-timelord** [comment]
Using pathlib in Python
pathlib is a modern and powerful library for handling filesystem paths and can be used to determine the correct location of user directories.

Windows 10
On Windows, the os library provides a straightforward way to fetch special folder paths using environment variables. Specifically, the Documents folder can be accessed via os.environ or os.path.expanduser.

Linux
On Linux, the Documents folder is typically located under ~/Documents.

import os
from pathlib import Path
import platform

def get_documents_folder():
    if platform.system() == "Windows":
        # Use Path from pathlib to access the "Documents" folder in Windows
        documents_path = Path(os.environ["USERPROFILE"]) / "Documents"
    else:
        # Use Path to access the "Documents" folder in Linux
        documents_path = Path.home() / "Documents"
    
    # Check if the path exists
    if not documents_path.exists():
        raise FileNotFoundError(f"Documents folder not found at {documents_path}")
    
    return documents_path

# Example usage
try:
    documents_folder = get_documents_folder()
    print(f"My Documents folder is located at: {documents_folder}")
except Exception as e:
    print(f"Error: {e}")

**Comment by Leidtier** [comment]
I have commited a PR #343 to fix this. 
@wiseman-timelord could you please check if this simple change is enough to fix the issue for you?
