### ISSUE TITLE
Mantella stuck at 'Listening' prompt

### ISSUE THREAD

**Issue by Shrikester** [art-from-the-machine/Mantella#424]
Skyrim VR
Reverb G2 Headset
Win10 22H2

I am able to start a conversation using the 'I want to speak with you option'. The NPC will deliver their line but then the prompt stays at 'Listening'. I have done the following:

- Changed the audio threshold up and down from 175
- Checked there are credits on the Open Router account
- Verified that the headset mic is picking up sound (via control panel)
- Tried different LLMs
- Tried different TTS (XTTS and Piper)

I am also using the mod Dragonborn Speaks Naturally and that works fine (reading lines, equipping favorites etc.) so I know the mic is picking up my voice.

**Comment by Smuckyyy** [comment]
How do you change the audio threshold? I saw it said MantellaSoftware/config.ini, but where exactly is that?

**Comment by adriic** [comment]
Hey, I am having the same issue, have you find a solution yet?

**Comment by Shrikester** [comment]
The only thing that worked for me was a complete re-install of Skyrim and the wabbajack modlist (MGO)

**Comment by Antonymous90** [comment]
I found a way. I had to go into the mod settings through MCM and disable the microphone. Then, I left only the text mode enabled, and the NPCs responded normally. After that, I reactivated the microphone and it worked, and from then on it kept working fine.

**Comment by Shrikester** [comment]
Wow ! If this works , you're a genius ! Mine is working because I did a complete re-install but I'll post this on the Mad Gods Overhaul Discord where others had the same issue
