### ISSUE TITLE
the option for google collab alternative dont work

### ISSUE THREAD

**Issue by alberto64674yt** [art-from-the-machine/Mantella#65]
followed all steps on: koboldcpp google colab notebook (Free cloud service, potentially spotty access / availablity)

but at least to me the collab dont give a link...  this is all the collab thows when finishing executing the command (play button): 

/content
Cloning into 'koboldcpp'...
remote: Enumerating objects: 14845, done.
remote: Counting objects: 100% (14844/14844), done.
remote: Compressing objects: 100% (4447/4447), done.
remote: Total 14845 (delta 10520), reused 14330 (delta 10334), pack-reused 1
Receiving objects: 100% (14845/14845), 65.03 MiB | 19.73 MiB/s, done.
Resolving deltas: 100% (10520/10520), done.
/content/koboldcpp
Finding prebuilt binary for 1.48
--2023-11-04 18:22:13--  https://kcppcolab.concedo.workers.dev/?1.48
Resolving kcppcolab.concedo.workers.dev (kcppcolab.concedo.workers.dev)... 104.21.71.155, 172.67.145.201, 2606:4700:3033::6815:479b, ...
Connecting to kcppcolab.concedo.workers.dev (kcppcolab.concedo.workers.dev)|104.21.71.155|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://huggingface.co/concedo/koboldcpp/resolve/main/prebuilt_binaries/1.48.so [following]
--2023-11-04 18:22:13--  https://huggingface.co/concedo/koboldcpp/resolve/main/prebuilt_binaries/1.48.so
Resolving huggingface.co (huggingface.co)... 18.172.134.4, 18.172.134.24, 18.172.134.88, ...
Connecting to huggingface.co (huggingface.co)|18.172.134.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://cdn-lfs.huggingface.co/repos/d2/2b/d22bcaf50ec2e655ec6dd5cef052361ab764809fb0e020f1f0128ab245ffe8e6/62a4fbe4518db9c73476368d3d0fded7c84b6974b75bd1c27fb1f08e392b7db7?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%271.48.so%3B+filename%3D%221.48.so%22%3B&response-content-type=application%2Foctet-stream&Expires=1699381333&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY5OTM4MTMzM319LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy5odWdnaW5nZmFjZS5jby9yZXBvcy9kMi8yYi9kMjJiY2FmNTBlYzJlNjU1ZWM2ZGQ1Y2VmMDUyMzYxYWI3NjQ4MDlmYjBlMDIwZjFmMDEyOGFiMjQ1ZmZlOGU2LzYyYTRmYmU0NTE4ZGI5YzczNDc2MzY4ZDNkMGZkZWQ3Yzg0YjY5NzRiNzViZDFjMjdmYjFmMDhlMzkyYjdkYjc%7EcmVzcG9uc2UtY29udGVudC1kaXNwb3NpdGlvbj0qJnJlc3BvbnNlLWNvbnRlbnQtdHlwZT0qIn1dfQ__&Signature=PCGoTcbSWGCTm9Y9c1JNGp9eiJ2PH8LN85JeOFZwPyCO9HlF7OCQhZN7KOh7XhdUZy1EhWHx4Y9RgKbbzJRTBeQ528AlUWq%7ER1LLvz%7E3lmS6nlHh-TWQ5d4OgNiAdJFknpImtVuk6h-Uyf0uasKJMvwJiGTjNFuQ50d85CsKvkL7jKlikMWi8V-NQoSArDTH4EDRFzWNbKNT8iJLrXtgV1Y6JxZrzl-cjx4QirHhWKC%7EEHJeIWYVv7K1AnR4Q0quyD48N%7E%7Ebd-YneULGGEbWxjmcv2QRrh4%7EImzCUr9J2DxspfW7qMCAkXgRRkLnOezCglnTe7aPkacgeLhanCtk8w__&Key-Pair-Id=KVTP0A1DKRTAX [following]
--2023-11-04 18:22:14--  https://cdn-lfs.huggingface.co/repos/d2/2b/d22bcaf50ec2e655ec6dd5cef052361ab764809fb0e020f1f0128ab245ffe8e6/62a4fbe4518db9c73476368d3d0fded7c84b6974b75bd1c27fb1f08e392b7db7?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%271.48.so%3B+filename%3D%221.48.so%22%3B&response-content-type=application%2Foctet-stream&Expires=1699381333&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY5OTM4MTMzM319LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy5odWdnaW5nZmFjZS5jby9yZXBvcy9kMi8yYi9kMjJiY2FmNTBlYzJlNjU1ZWM2ZGQ1Y2VmMDUyMzYxYWI3NjQ4MDlmYjBlMDIwZjFmMDEyOGFiMjQ1ZmZlOGU2LzYyYTRmYmU0NTE4ZGI5YzczNDc2MzY4ZDNkMGZkZWQ3Yzg0YjY5NzRiNzViZDFjMjdmYjFmMDhlMzkyYjdkYjc%7EcmVzcG9uc2UtY29udGVudC1kaXNwb3NpdGlvbj0qJnJlc3BvbnNlLWNvbnRlbnQtdHlwZT0qIn1dfQ__&Signature=PCGoTcbSWGCTm9Y9c1JNGp9eiJ2PH8LN85JeOFZwPyCO9HlF7OCQhZN7KOh7XhdUZy1EhWHx4Y9RgKbbzJRTBeQ528AlUWq%7ER1LLvz%7E3lmS6nlHh-TWQ5d4OgNiAdJFknpImtVuk6h-Uyf0uasKJMvwJiGTjNFuQ50d85CsKvkL7jKlikMWi8V-NQoSArDTH4EDRFzWNbKNT8iJLrXtgV1Y6JxZrzl-cjx4QirHhWKC%7EEHJeIWYVv7K1AnR4Q0quyD48N%7E%7Ebd-YneULGGEbWxjmcv2QRrh4%7EImzCUr9J2DxspfW7qMCAkXgRRkLnOezCglnTe7aPkacgeLhanCtk8w__&Key-Pair-Id=KVTP0A1DKRTAX
Resolving cdn-lfs.huggingface.co (cdn-lfs.huggingface.co)... 18.154.185.26, 18.154.185.94, 18.154.185.27, ...
Connecting to cdn-lfs.huggingface.co (cdn-lfs.huggingface.co)|18.154.185.26|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4033656 (3.8M) [application/octet-stream]
Saving to: ‘dlfile.tmp’

dlfile.tmp          100%[===================>]   3.85M  --.-KB/s    in 0.1s    

2023-11-04 18:22:14 (39.1 MB/s) - ‘dlfile.tmp’ saved [4033656/4033656]

Prebuilt Binary Exists
Build Skipped
--2023-11-04 18:22:14--  https://huggingface.co/KoboldAI/LLaMA2-13B-Tiefighter-GGUF/resolve/main/LLaMA2-13B-Tiefighter.Q4_K_M.gguf
Resolving huggingface.co (huggingface.co)... 18.172.134.4, 18.172.134.24, 18.172.134.88, ...
Connecting to huggingface.co (huggingface.co)|18.172.134.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://cdn-lfs.huggingface.co/repos/64/d4/64d41122364f34dc3f3f027a22dea4901d8f511d7f16497a8fc1e8ed3b9b06b7/ea97134b32f2e282cc0e245f9d53902115d3b17b84b7c18b1190bf095220c582?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%27LLaMA2-13B-Tiefighter.Q4_K_M.gguf%3B+filename%3D%22LLaMA2-13B-Tiefighter.Q4_K_M.gguf%22%3B&Expires=1699381334&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY5OTM4MTMzNH19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy5odWdnaW5nZmFjZS5jby9yZXBvcy82NC9kNC82NGQ0MTEyMjM2NGYzNGRjM2YzZjAyN2EyMmRlYTQ5MDFkOGY1MTFkN2YxNjQ5N2E4ZmMxZThlZDNiOWIwNmI3L2VhOTcxMzRiMzJmMmUyODJjYzBlMjQ1ZjlkNTM5MDIxMTVkM2IxN2I4NGI3YzE4YjExOTBiZjA5NTIyMGM1ODI%7EcmVzcG9uc2UtY29udGVudC1kaXNwb3NpdGlvbj0qIn1dfQ__&Signature=Yk0sj-D5ANdV59NSWR%7ErIH027sLYkHXeyG5lC3lzpasaeYKstBhpOSiKtxKU9H7kHRhGymAP8dg7WH38wwxGyRZjgunGH4hYHMxmpS-KBgjzGV55ID1dFTBPPDNAsYJuQUbC91dIJgAZqdFYiXPruk3SntgCVzpA0p2MMl6r5kf8wrezumv-D6QhOSxBzh2E-mUcLzomwiko8d5gvMS58C2lt8G-C99%7E0I%7EkW9q-FK83pyHdy4tVprcSzvtK6R14yeL87Sb4ZENiqc1BWO9uJuklvczYEyOdeKW5RI0rkS-KzQb1WJioys4j5IXDFp7%7EutSXZ-IZKJChZfSb26uz3g__&Key-Pair-Id=KVTP0A1DKRTAX [following]
--2023-11-04 18:22:14--  https://cdn-lfs.huggingface.co/repos/64/d4/64d41122364f34dc3f3f027a22dea4901d8f511d7f16497a8fc1e8ed3b9b06b7/ea97134b32f2e282cc0e245f9d53902115d3b17b84b7c18b1190bf095220c582?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%27LLaMA2-13B-Tiefighter.Q4_K_M.gguf%3B+filename%3D%22LLaMA2-13B-Tiefighter.Q4_K_M.gguf%22%3B&Expires=1699381334&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY5OTM4MTMzNH19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy5odWdnaW5nZmFjZS5jby9yZXBvcy82NC9kNC82NGQ0MTEyMjM2NGYzNGRjM2YzZjAyN2EyMmRlYTQ5MDFkOGY1MTFkN2YxNjQ5N2E4ZmMxZThlZDNiOWIwNmI3L2VhOTcxMzRiMzJmMmUyODJjYzBlMjQ1ZjlkNTM5MDIxMTVkM2IxN2I4NGI3YzE4YjExOTBiZjA5NTIyMGM1ODI%7EcmVzcG9uc2UtY29udGVudC1kaXNwb3NpdGlvbj0qIn1dfQ__&Signature=Yk0sj-D5ANdV59NSWR%7ErIH027sLYkHXeyG5lC3lzpasaeYKstBhpOSiKtxKU9H7kHRhGymAP8dg7WH38wwxGyRZjgunGH4hYHMxmpS-KBgjzGV55ID1dFTBPPDNAsYJuQUbC91dIJgAZqdFYiXPruk3SntgCVzpA0p2MMl6r5kf8wrezumv-D6QhOSxBzh2E-mUcLzomwiko8d5gvMS58C2lt8G-C99%7E0I%7EkW9q-FK83pyHdy4tVprcSzvtK6R14yeL87Sb4ZENiqc1BWO9uJuklvczYEyOdeKW5RI0rkS-KzQb1WJioys4j5IXDFp7%7EutSXZ-IZKJChZfSb26uz3g__&Key-Pair-Id=KVTP0A1DKRTAX
Resolving cdn-lfs.huggingface.co (cdn-lfs.huggingface.co)... 18.154.185.26, 18.154.185.94, 18.154.185.27, ...
Connecting to cdn-lfs.huggingface.co (cdn-lfs.huggingface.co)|18.154.185.26|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7865956288 (7.3G) [binary/octet-stream]
Saving to: ‘model.ggml’

model.ggml          100%[===================>]   7.33G   238MB/s    in 31s     

2023-11-04 18:22:46 (238 MB/s) - ‘model.ggml’ saved [7865956288/7865956288]

***
Welcome to KoboldCpp - Version 1.48
Attempting to use CuBLAS library for faster prompt ingestion. A compatible CuBLAS will be required.
Initializing dynamic library: koboldcpp_cublas.so
==========
Namespace(model=None, model_param='model.ggml', port=5001, port_param=5001, host='', launch=False, lora=None, config=None, threads=1, blasthreads=1, highpriority=False, contextsize=4096, blasbatchsize=512, ropeconfig=[0.0, 10000.0], smartcontext=False, noshift=False, bantokens=None, forceversion=0, nommap=False, usemlock=False, noavx2=False, debugmode=-1, skiplauncher=False, hordeconfig=['concedo', '1', '1'], noblas=False, useclblast=None, usecublas=['0', 'mmq'], gpulayers=43, tensor_split=None, onready='', multiuser=True, remotetunnel=True, foreground=False)
==========
Loading model: /content/koboldcpp/model.ggml 
[Threads: 1, BlasThreads: 1, SmartContext: False, ContextShift: True]

---
Identified as LLAMA model: (ver 6)
Attempting to Load...
---
Using automatic RoPE scaling (scale:1.000, base:10000.0)
System Info: AVX = 1 | AVX2 = 1 | AVX512 = 1 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | 
ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   maybe
ggml_init_cublas: CUDA_USE_TENSOR_CORES: maybe
ggml_init_cublas: found 1 CUDA devices:
  Device 0: Tesla T4, compute capability 7.5

i cant see any link to use that... just download links that have used to get this working but not any link to use actually that ai

**Comment by teddybear082** [comment]
Try it again, it should work now, there was a period of time when cloudflare was having issues resulting in Colabs that depended on it not generating the links
