### ISSUE TITLE
Use LiteLLM for more LLM support

### ISSUE THREAD

**Issue by Raphtor** [art-from-the-machine/Mantella#68]
Using LiteLLM would greatly increase the number of supported LLMs, as well as simplify your setup instructions. I will make a PR.

**Comment by Raphtor** [comment]
Realized this was the point of using OpenRouter, but LiteLLM also supports that!

**Comment by teddybear082** [comment]
Anything that uses an openAI API is already supported out of the box, just put in whatever URL:port/v1 litellm generates for you, and it should work.

**Comment by Raphtor** [comment]
Yup, that would be easier!
