### ISSUE TITLE
Could not find _mantella__skyrim_folder.txt

### ISSUE THREAD

**Issue by HagstorMall** [art-from-the-machine/Mantella#97]
Hi,
I can't solve this problem: when i launch Matella it's says: Warning: Could not find _mantella__skyrim_folder.txt in (my skyrim folder)
I have the Skyrim 1.6.1130 version, so i took the AE version of Papyrus and the AE library. 
I can see that Mantella files are added in my skyrim folder, such as aggro, conversation hotkey file... Only the  _mantella__skyrim_folder.txt is missing, even if i cast the spell in the game and make quick save and load.
Any idea ?

**Comment by Pendrokar** [comment]
@HagstorMall make sure check this part of the FAQ first:
https://github.com/art-from-the-machine/Mantella?tab=readme-ov-file#conversation-ends-as-soon-as-spell-is-cast--errno-2-no-such-file-or-directory-pathtoskyrim-special-editionsome_text_filetxt

**Comment by Monioum** [comment]
Yeah. I can't find the file. I have GOG & AE edition.

My directories are correct as far as I'm concerned.
skyrim_folder = C:\Games\Common\GOG Galaxy\Skyrim Anniversary Edition
xvasynth_folder = C:\Games\Common\xVASynth v3.0.0 Main app-44184-3-0-0-1684850032
mod_folder = C:\Games\Common\GOG Galaxy\Skyrim Anniversary Edition\Data

Tried PapyrusUtil GOG, or AE SE

I'm stuck. Any help woudl be greatly appreciated.
